FROM python:3.6.5

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Get that sweet pipenv action
RUN pip install pipenv
COPY Pipfile /usr/src/app/Pipfile
COPY Pipfile.lock /usr/src/app/Pipfile.lock
RUN pipenv install --system

COPY . /usr/src/app

CMD python manage.py run -h 0.0.0.0